emit:
  - 'typespec-typescript-emitter'
  - 'tinybase-emitter'
  - 'tinybase-template-emitter'
options:
  'typespec-typescript-emitter':
    root-namespaces:
      - 'IssueTracker'
    out-dir: '{cwd}/../src/generated'
    enable-types: true
    enable-typeguards: false
    enable-routes: false
    enable-routed-typemap: false
    enable-routed-path-params: false
    import-file-extensions: false
    string-nominal-enums: false
    serializable-date-types: false
  'tinybase-emitter':
    output-dir: '{cwd}/../src/generated'
  'tinybase-template-emitter':
    output-dir: '{cwd}/../src/generated'
